apiVersion: v1
kind: Pod
metadata:
  name: mongopod
  namespace: nsmongo

spec:
    volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: pvc
    containers:
      - name: mongodb
        image: mongo
        ports:
          - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: pvc