apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongopv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  #storageClassName: mongopv
  #local:
    #path: /data/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: In
              values:
                - persistente
