apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongostate
  namespace: nsmongo
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodbservice
  replicas: 1
  template:

    metadata:
      labels:
        app: mongodb
        selector: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongopvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - persistente


  volumeClaimTemplates:
    - metadata:
        name: mongopvc
        namespace: nsmongo
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: mongopv