apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongopv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  #storageClassName: mongopv
  #local:
    #path: /data/db
  gcePersistentDisk:
    pdName: disk-mongo
    fsType: ext4
