apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: nsmongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: mongopv
