apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pruebabook
  namespace: argocd
spec:
  source:
    path: pruebacd
    repoURL: https://github.com/enriqueav99/pycicd.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nspy
  project: pruebacd
